import {
  Shipment,
  Driver,
  LogisticsAlert,
  ExpenseRecord,
  DailyTrend,
  HourlyHeatmap,
  FuelTrend,
  Vehicle,
  RoutePlan,
  InventoryItem,
  WarehouseHub,
  InvoiceRecord,
  RateTariff,
  SystemPermission,
  AIGovernanceConfig,
} from "@/types/logistics";

export const INITIAL_DRIVERS: Driver[] = [
  {
    id: "drv-101",
    name: "Marcus Vance",
    phone: "+1 (555) 234-5678",
    avatar: "https://picsum.photos/seed/driver1/120/120",
    status: "On Duty",
    vehicleType: "Heavy Duty Van",
    vehicleNo: "DHL-V-901",
    currentLat: 51.5074,
    currentLng: -0.1278,
    assignedShipmentIds: ["ship-001", "ship-002"],
    rating: 4.9,
    completedToday: 14,
    fuelLevelPct: 82,
    activeRouteName: "Central London Hub -> Heathrow Express",
  },
  {
    id: "drv-102",
    name: "Aisha Bello",
    phone: "+234 803 123 4567",
    avatar: "https://picsum.photos/seed/driver2/120/120",
    status: "On Duty",
    vehicleType: "Refrigerated Cargo Truck",
    vehicleNo: "DHL-T-404",
    currentLat: 6.5244,
    currentLng: 3.3792,
    assignedShipmentIds: ["ship-003"],
    rating: 4.8,
    completedToday: 9,
    fuelLevelPct: 65,
    activeRouteName: "Ikeja Logistics Corridor -> Victoria Island",
  },
  {
    id: "drv-103",
    name: "David Chen",
    phone: "+1 (555) 987-6543",
    avatar: "https://picsum.photos/seed/driver3/120/120",
    status: "Available",
    vehicleType: "Express Courier Van",
    vehicleNo: "DHL-V-210",
    currentLat: 40.7128,
    currentLng: -74.006,
    assignedShipmentIds: [],
    rating: 4.95,
    completedToday: 18,
    fuelLevelPct: 94,
    activeRouteName: "New York Metro Area",
  },
  {
    id: "drv-104",
    name: "Sophie Martin",
    phone: "+33 612 345 678",
    avatar: "https://picsum.photos/seed/driver4/120/120",
    status: "On Duty",
    vehicleType: "Electric Cargo Van",
    vehicleNo: "DHL-EV-05",
    currentLat: 48.8566,
    currentLng: 2.3522,
    assignedShipmentIds: ["ship-005"],
    rating: 4.7,
    completedToday: 11,
    fuelLevelPct: 48,
    activeRouteName: "Paris Intra-muros Express",
  },
  {
    id: "drv-105",
    name: "Klaus Schmidt",
    phone: "+49 171 234567",
    avatar: "https://picsum.photos/seed/driver5/120/120",
    status: "Maintenance",
    vehicleType: "Articulated Freighter",
    vehicleNo: "DHL-F-882",
    currentLat: 50.1109,
    currentLng: 8.6821,
    assignedShipmentIds: [],
    rating: 4.6,
    completedToday: 0,
    fuelLevelPct: 15,
    activeRouteName: "Frankfurt Central Depot",
  },
  {
    id: "drv-106",
    name: "Taro Tanaka",
    phone: "+81 90 1234 5678",
    avatar: "https://picsum.photos/seed/driver6/120/120",
    status: "Off Duty",
    vehicleType: "Compact Delivery Sprinter",
    vehicleNo: "DHL-V-118",
    currentLat: 35.6762,
    currentLng: 139.6503,
    assignedShipmentIds: [],
    rating: 5.0,
    completedToday: 22,
    fuelLevelPct: 100,
    activeRouteName: "Tokyo Haneda Hub",
  },
];

export const INITIAL_SHIPMENTS: Shipment[] = [
  {
    id: "ship-001",
    trackingId: "DHL-8942-01",
    orderId: "ORD-2026-901",
    customerName: "AeroTech Systems Ltd",
    customerPhone: "+44 20 7946 0912",
    senderName: "Global Silicon Supplies",
    senderEmail: "shipping@globalsilicon.example",
    senderPhone: "+44 20 7946 0912",
    senderAddress: "12 Logistics Way, Slough Depot, UK",
    recipientEmail: "receiving@aerotech.example",
    recipientPhone: "+44 20 7946 0912",
    recipientAddress: "45 Tech City Blvd, Shoreditch, London, UK",
    originCity: "Slough, UK",
    destinationCity: "London, UK",
    status: "In Transit",
    priority: "Overnight",
    weightKg: 14.5,
    parcelType: "High-Value Electronics",
    estimatedDelivery: "2026-08-08 17:30",
    createdAt: "2026-08-08 08:15",
    driverId: "drv-101",
    driverName: "Marcus Vance",
    vehicleNo: "DHL-V-901",
    currentLocation: {
      lat: 51.512,
      lng: -0.118,
      address: "A40 Westway Highway, en route to Central London",
    },
    routePoints: [
      {
        lat: 51.509,
        lng: -0.21,
        name: "Slough Distribution Center",
        completed: true,
        timestamp: "08:30",
      },
      {
        lat: 51.512,
        lng: -0.15,
        name: "Paddington Sorting Facility",
        completed: true,
        timestamp: "14:20",
      },
      {
        lat: 51.512,
        lng: -0.118,
        name: "Holborn Transit Checkpoint",
        completed: false,
      },
      {
        lat: 51.524,
        lng: -0.082,
        name: "Shoreditch Tech Hub (Destination)",
        completed: false,
      },
    ],
    costUsd: 42.5,
    revenueUsd: 135.0,
    fuelCostUsd: 12.4,
    timeline: [
      {
        id: "t1",
        status: "Order Placed",
        location: "Slough Depot",
        timestamp: "2026-08-08 08:15",
        note: "Electronic shipping instructions received. Package ready for pickup in London.",
        updatedBy: "DHL",
      },
      {
        id: "t2",
        status: "In Transit",
        location: "Slough Distribution Center",
        timestamp: "2026-08-08 08:30",
        note: "Package loaded and dispatch scanned.",
        updatedBy: "DHL",
      },
      {
        id: "t3",
        status: "In Transit",
        location: "Paddington Sorting Facility",
        timestamp: "2026-08-08 14:20",
        note: "Passed mid-route security check.",
        updatedBy: "DHL",
      },
    ],
    proofOfDelivery: {
      verified: false,
      otpCode: "849201",
    },
  },
  {
    id: "ship-002",
    trackingId: "DHL-3301-88",
    orderId: "ORD-2026-884",
    customerName: "BioHealth Pharma",
    customerPhone: "+44 20 7123 4567",
    senderName: "Oxford Biocentres",
    senderEmail: "dispatch@oxfordbiocentres.example",
    senderPhone: "+44 20 7123 4567",
    senderAddress: "Bio Park Avenue, Oxford, UK",
    recipientEmail: "receiving@biohealth.example",
    recipientPhone: "+44 20 7123 4567",
    recipientAddress: "Queen Mary Medical Wing, Whitechapel, London, UK",
    originCity: "Oxford, UK",
    destinationCity: "London, UK",
    status: "Delayed",
    priority: "Express",
    weightKg: 8.2,
    parcelType: "Temperature Sensitive Medical",
    estimatedDelivery: "2026-08-08 16:00",
    createdAt: "2026-08-08 07:00",
    driverId: "drv-101",
    driverName: "Marcus Vance",
    vehicleNo: "DHL-V-901",
    currentLocation: {
      lat: 51.515,
      lng: -0.142,
      address: "Marylebone Road (Heavy Traffic Hold)",
    },
    routePoints: [
      {
        lat: 51.752,
        lng: -1.257,
        name: "Oxford Bio Depot",
        completed: true,
        timestamp: "07:30",
      },
      {
        lat: 51.515,
        lng: -0.142,
        name: "Marylebone Congestion Zone",
        completed: false,
      },
      {
        lat: 51.519,
        lng: -0.061,
        name: "Whitechapel Medical Center",
        completed: false,
      },
    ],
    costUsd: 65.0,
    revenueUsd: 190.0,
    fuelCostUsd: 18.2,
    timeline: [
      {
        id: "t1",
        status: "Pending",
        location: "Oxford",
        timestamp: "2026-08-08 07:00",
        note: "Cold-chain parcel pre-logged.",
        updatedBy: "DHL",
      },
      {
        id: "t2",
        status: "In Transit",
        location: "Oxford Bio Depot",
        timestamp: "2026-08-08 07:30",
        note: "Refrigerated container verified at 4°C.",
        updatedBy: "DHL",
      },
      {
        id: "t3",
        status: "Delayed",
        location: "Marylebone Road",
        timestamp: "2026-08-08 15:45",
        note: "Severe traffic congestion on M4/A40 entrance corridor. SLA pushed back 45 mins.",
        updatedBy: "DHL",
      },
    ],
    flaggedForDelay: true,
    delayReason: "M4 Highway Congestion & Roadwork Hold",
    proofOfDelivery: {
      verified: false,
      otpCode: "330188",
    },
  },
  {
    id: "ship-003",
    trackingId: "DHL-7720-49",
    orderId: "ORD-2026-441",
    customerName: "Jumia Express Retail",
    customerPhone: "+234 812 000 9988",
    senderName: "DHL Ikeja Mega Hub",
    senderEmail: "ikeja.dispatch@dhl.example",
    senderPhone: "+234 812 000 9988",
    senderAddress: "Plot 4 Airport Road, Ikeja, Lagos, Nigeria",
    recipientEmail: "receiving@jumia.example",
    recipientPhone: "+234 812 000 9988",
    recipientAddress: "18 Commercial Avenue, Yaba, Lagos, Nigeria",
    originCity: "Ikeja, Lagos",
    destinationCity: "Yaba, Lagos",
    status: "Out for Delivery",
    priority: "Express",
    weightKg: 5.0,
    parcelType: "Consumer Electronics & Wearables",
    estimatedDelivery: "2026-08-08 18:00",
    createdAt: "2026-08-08 10:00",
    driverId: "drv-102",
    driverName: "Aisha Bello",
    vehicleNo: "DHL-T-404",
    currentLocation: {
      lat: 6.518,
      lng: 3.382,
      address: "Third Mainland Approach, Yaba Exit",
    },
    routePoints: [
      {
        lat: 6.58,
        lng: 3.32,
        name: "Ikeja Airfreight Terminal",
        completed: true,
        timestamp: "11:00",
      },
      { lat: 6.518, lng: 3.382, name: "Yaba Commercial Ave", completed: false },
    ],
    costUsd: 28.0,
    revenueUsd: 85.0,
    fuelCostUsd: 8.5,
    timeline: [
      {
        id: "t1",
        status: "Pending",
        location: "Ikeja Hub",
        timestamp: "2026-08-08 10:00",
        note: "Cargo scanned at airfreight terminal.",
        updatedBy: "DHL",
      },
      {
        id: "t2",
        status: "Out for Delivery",
        location: "Ikeja Hub",
        timestamp: "2026-08-08 11:30",
        note: "Out for final mile delivery with Driver Aisha Bello.",
        updatedBy: "DHL",
      },
    ],
    proofOfDelivery: {
      verified: false,
      otpCode: "772049",
    },
  },
  {
    id: "ship-004",
    trackingId: "DHL-1109-55",
    orderId: "ORD-2026-112",
    customerName: "Manhattan Boutique Imports",
    customerPhone: "+1 212 555 0199",
    senderName: "JFK Cargo Logistics Gateway",
    senderEmail: "jfk.dispatch@dhl.example",
    senderPhone: "+1 212 555 0199",
    senderAddress: "Building 77, JFK Airport, NY, USA",
    recipientEmail: "receiving@manhattanboutique.example",
    recipientPhone: "+1 212 555 0199",
    recipientAddress: "742 Fifth Avenue, Manhattan, NY, USA",
    originCity: "JFK Airport, NY",
    destinationCity: "New York, NY",
    status: "Delivered",
    priority: "Standard",
    weightKg: 22.0,
    parcelType: "Designer Apparel & Footwear",
    estimatedDelivery: "2026-08-08 14:00",
    actualDelivery: "2026-08-08 13:42",
    createdAt: "2026-08-07 18:30",
    driverId: "drv-103",
    driverName: "David Chen",
    vehicleNo: "DHL-V-210",
    currentLocation: {
      lat: 40.762,
      lng: -73.974,
      address: "Fifth Ave & 57th St, Manhattan",
    },
    routePoints: [
      {
        lat: 40.641,
        lng: -73.778,
        name: "JFK Gateway Depot",
        completed: true,
        timestamp: "08:00",
      },
      {
        lat: 40.762,
        lng: -73.974,
        name: "Fifth Avenue Boutique (Delivered)",
        completed: true,
        timestamp: "13:42",
      },
    ],
    costUsd: 38.0,
    revenueUsd: 110.0,
    fuelCostUsd: 11.2,
    timeline: [
      {
        id: "t1",
        status: "In Transit",
        location: "JFK Airport",
        timestamp: "2026-08-08 08:00",
        note: "Customs cleared. Loaded into express sprinter.",
        updatedBy: "DHL",
      },
      {
        id: "t2",
        status: "Out for Delivery",
        location: "Manhattan Midtown Hub",
        timestamp: "2026-08-08 11:15",
        note: "En route to customer.",
        updatedBy: "DHL",
      },
      {
        id: "t3",
        status: "Delivered",
        location: "Fifth Avenue",
        timestamp: "2026-08-08 13:42",
        note: "Delivered safely to receiving dock. Signed by James Miller (Store Mgr).",
        updatedBy: "DHL",
      },
    ],
    proofOfDelivery: {
      verified: true,
      verifiedAt: "2026-08-08 13:42",
      signedByCustomerName: "James Miller",
      photoUrl: "https://picsum.photos/seed/pod1/400/300",
      signatureUrl:
        'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="200" height="80"><path d="M 10 40 Q 50 10 90 50 T 170 30" stroke="%23d40511" stroke-width="3" fill="none"/></svg>',
    },
  },
  {
    id: "ship-005",
    trackingId: "DHL-6641-02",
    orderId: "ORD-2026-664",
    customerName: "LVMH European Logistics",
    customerPhone: "+33 1 40 00 12 34",
    senderName: "Orly Cargo Terminal",
    senderEmail: "orly.dispatch@dhl.example",
    senderPhone: "+33 1 40 00 12 34",
    senderAddress: "Orly Airport, Paris, France",
    recipientEmail: "receiving@lvmh.example",
    recipientPhone: "+33 1 40 00 12 34",
    recipientAddress: "12 Avenue Montaigne, 75008 Paris, France",
    originCity: "Orly, France",
    destinationCity: "Paris, France",
    status: "In Transit",
    priority: "Express",
    weightKg: 11.8,
    parcelType: "Luxury Goods & Timepieces",
    estimatedDelivery: "2026-08-08 18:30",
    createdAt: "2026-08-08 09:30",
    driverId: "drv-104",
    driverName: "Sophie Martin",
    vehicleNo: "DHL-EV-05",
    currentLocation: {
      lat: 48.845,
      lng: 2.325,
      address: "Boulevard Saint-Germain, Paris",
    },
    routePoints: [
      {
        lat: 48.726,
        lng: 2.365,
        name: "Orly Cargo Hub",
        completed: true,
        timestamp: "10:15",
      },
      {
        lat: 48.845,
        lng: 2.325,
        name: "Saint-Germain Checkpoint",
        completed: false,
      },
      {
        lat: 48.866,
        lng: 2.308,
        name: "Avenue Montaigne Flagship",
        completed: false,
      },
    ],
    costUsd: 31.0,
    revenueUsd: 98.0,
    fuelCostUsd: 4.8, // Electric EV low fuel expense
    timeline: [
      {
        id: "t1",
        status: "Pending",
        location: "Orly Depot",
        timestamp: "2026-08-08 09:30",
        note: "Order registered in Paris e-fleet system.",
        updatedBy: "DHL",
      },
      {
        id: "t2",
        status: "In Transit",
        location: "Orly Airport",
        timestamp: "2026-08-08 10:15",
        note: "Dispatched in EV Sprinter 05.",
        updatedBy: "DHL",
      },
    ],
    proofOfDelivery: {
      verified: false,
      otpCode: "664102",
    },
  },
  {
    id: "ship-006",
    trackingId: "DHL-5582-90",
    orderId: "ORD-2026-558",
    customerName: "Siemens Energy AG",
    customerPhone: "+49 89 2345 6789",
    senderName: "DHL Frankfurt Global Freight Gateway",
    senderEmail: "frankfurt.dispatch@dhl.example",
    senderPhone: "+49 89 2345 6789",
    senderAddress: "CargoCity Süd, Frankfurt Airport, Germany",
    recipientEmail: "receiving@siemens.example",
    recipientPhone: "+49 89 2345 6789",
    recipientAddress: "Siemens Turbine Werk, Nuremberg, Germany",
    originCity: "Frankfurt, Germany",
    destinationCity: "Nuremberg, Germany",
    status: "Pending",
    priority: "Standard",
    weightKg: 140.0,
    parcelType: "Industrial Machinery Parts",
    estimatedDelivery: "2026-08-09 12:00",
    createdAt: "2026-08-08 14:00",
    currentLocation: {
      lat: 50.0379,
      lng: 8.5622,
      address: "Frankfurt Freight Terminal Dock B4",
    },
    routePoints: [
      {
        lat: 50.0379,
        lng: 8.5622,
        name: "Frankfurt CargoCity",
        completed: false,
      },
      { lat: 49.4521, lng: 11.0767, name: "Nuremberg Plant", completed: false },
    ],
    costUsd: 180.0,
    revenueUsd: 520.0,
    fuelCostUsd: 45.0,
    timeline: [
      {
        id: "t1",
        status: "Pending",
        location: "Frankfurt Hub",
        timestamp: "2026-08-08 14:00",
        note: "Awaiting heavy vehicle assignment.",
        updatedBy: "DHL",
      },
    ],
    proofOfDelivery: {
      verified: false,
    },
  },
  {
    id: "ship-007",
    trackingId: "DHL-9912-34",
    orderId: "ORD-2026-991",
    customerName: "Sony Electronics Asia",
    customerPhone: "+81 3 6742 1111",
    senderName: "Narita Air Logistics Hub",
    senderEmail: "narita.dispatch@dhl.example",
    senderPhone: "+81 3 6742 1111",
    senderAddress: "Chiba, Narita Airport, Tokyo, Japan",
    recipientEmail: "receiving@sony.example",
    recipientPhone: "+81 3 6742 1111",
    recipientAddress: "Ginza Sony Park Tower, Tokyo, Japan",
    originCity: "Narita, Japan",
    destinationCity: "Tokyo, Japan",
    status: "Canceled",
    priority: "Standard",
    weightKg: 3.4,
    parcelType: "Prototype Optics",
    estimatedDelivery: "2026-08-08 16:00",
    createdAt: "2026-08-08 06:00",
    currentLocation: {
      lat: 35.772,
      lng: 140.392,
      address: "Narita Customs Staging Bay",
    },
    routePoints: [
      {
        lat: 35.772,
        lng: 140.392,
        name: "Narita Cargo Terminal",
        completed: false,
      },
    ],
    costUsd: 15.0,
    revenueUsd: 0.0,
    fuelCostUsd: 0.0,
    timeline: [
      {
        id: "t1",
        status: "Pending",
        location: "Narita Depot",
        timestamp: "2026-08-08 06:00",
        note: "Manifest logged.",
        updatedBy: "DHL",
      },
      {
        id: "t2",
        status: "Canceled",
        location: "Narita Depot",
        timestamp: "2026-08-08 08:30",
        note: "Order canceled by customer request before dispatch.",
        updatedBy: "DHL",
      },
    ],
  },
];

export const INITIAL_ALERTS: LogisticsAlert[] = [
  {
    id: "alt-001",
    shipmentId: "ship-002",
    trackingId: "DHL-3301-88",
    type: "delay",
    severity: "high",
    message:
      "M4 Highway Corridor severe congestion. Shipment DHL-3301-88 delayed by 45 minutes.",
    timestamp: "15:45",
    resolved: false,
  },
  {
    id: "alt-002",
    shipmentId: "ship-006",
    trackingId: "DHL-5582-90",
    type: "capacity",
    severity: "medium",
    message:
      "Heavy cargo (140 kg) pending driver assignment at Frankfurt CargoCity.",
    timestamp: "14:10",
    resolved: false,
  },
  {
    id: "alt-003",
    shipmentId: "ship-001",
    trackingId: "DHL-8942-01",
    type: "sla_breach",
    severity: "low",
    message:
      "Approaching SLA window (< 60 mins remaining) for Overnight priority DHL-8942-01.",
    timestamp: "16:30",
    resolved: false,
  },
];

export const INITIAL_EXPENSES: ExpenseRecord[] = [
  {
    id: "exp-01",
    date: "2026-08-08",
    category: "fuel",
    amountUsd: 420.5,
    vehicleNo: "DHL-V-901",
    driverName: "Marcus Vance",
    note: "Diesel fill-up Slough Depot",
  },
  {
    id: "exp-02",
    date: "2026-08-08",
    category: "toll",
    amountUsd: 85.0,
    vehicleNo: "DHL-T-404",
    driverName: "Aisha Bello",
    note: "Lagos Island Toll Plaza",
  },
  {
    id: "exp-03",
    date: "2026-08-08",
    category: "maintenance",
    amountUsd: 640.0,
    vehicleNo: "DHL-F-882",
    driverName: "Klaus Schmidt",
    note: "Hydraulic lift inspection",
  },
  {
    id: "exp-04",
    date: "2026-08-07",
    category: "fuel",
    amountUsd: 380.0,
    vehicleNo: "DHL-V-210",
    driverName: "David Chen",
    note: "NY Shell Station",
  },
  {
    id: "exp-05",
    date: "2026-08-07",
    category: "driver_payout",
    amountUsd: 1200.0,
    vehicleNo: "Fleet All",
    driverName: "Multiple Drivers",
    note: "Weekly performance bonus",
  },
];

export const DAILY_TREND_DATA: DailyTrend[] = [
  { date: "Aug 02", delivered: 180, delayed: 8, pending: 12, totalVolume: 200 },
  {
    date: "Aug 03",
    delivered: 210,
    delayed: 14,
    pending: 15,
    totalVolume: 239,
  },
  {
    date: "Aug 04",
    delivered: 245,
    delayed: 10,
    pending: 18,
    totalVolume: 273,
  },
  {
    date: "Aug 05",
    delivered: 230,
    delayed: 18,
    pending: 20,
    totalVolume: 268,
  },
  {
    date: "Aug 06",
    delivered: 290,
    delayed: 12,
    pending: 22,
    totalVolume: 324,
  },
  { date: "Aug 07", delivered: 310, delayed: 9, pending: 25, totalVolume: 344 },
  {
    date: "Aug 08",
    delivered: 275,
    delayed: 11,
    pending: 30,
    totalVolume: 316,
  },
];

export const HOURLY_HEATMAP_DATA: HourlyHeatmap[] = [
  { hour: "08:00", dispatched: 45, delivered: 5 },
  { hour: "10:00", dispatched: 82, delivered: 34 },
  { hour: "12:00", dispatched: 60, delivered: 78 },
  { hour: "14:00", dispatched: 95, delivered: 88 },
  { hour: "16:00", dispatched: 40, delivered: 92 },
  { hour: "18:00", dispatched: 15, delivered: 64 },
  { hour: "20:00", dispatched: 5, delivered: 22 },
];

export const FUEL_TREND_DATA: FuelTrend[] = [
  {
    date: "Mon",
    fuelSpend: 1420,
    tollsSpend: 310,
    maintenanceSpend: 250,
    avgCostPerDelivery: 18.2,
  },
  {
    date: "Tue",
    fuelSpend: 1580,
    tollsSpend: 340,
    maintenanceSpend: 180,
    avgCostPerDelivery: 17.8,
  },
  {
    date: "Wed",
    fuelSpend: 1390,
    tollsSpend: 290,
    maintenanceSpend: 600,
    avgCostPerDelivery: 19.4,
  },
  {
    date: "Thu",
    fuelSpend: 1610,
    tollsSpend: 380,
    maintenanceSpend: 200,
    avgCostPerDelivery: 17.5,
  },
  {
    date: "Fri",
    fuelSpend: 1750,
    tollsSpend: 410,
    maintenanceSpend: 320,
    avgCostPerDelivery: 18.1,
  },
  {
    date: "Sat",
    fuelSpend: 1200,
    tollsSpend: 220,
    maintenanceSpend: 150,
    avgCostPerDelivery: 16.9,
  },
  {
    date: "Sun",
    fuelSpend: 980,
    tollsSpend: 180,
    maintenanceSpend: 100,
    avgCostPerDelivery: 16.2,
  },
];

export const INITIAL_VEHICLES: Vehicle[] = [
  {
    id: "veh-01",
    plateNo: "DHL-V-901",
    model: "Mercedes-Benz Sprinter 317 CDI",
    type: "Heavy Duty Van",
    status: "En Route",
    driverId: "drv-101",
    driverName: "Marcus Vance",
    fuelLevelPct: 82,
    mileageKm: 48920,
    nextServiceDate: "2026-09-15",
    maxPayloadKg: 1800,
    lastInspectionPassed: true,
    gpsDeviceId: "GPS-TRK-901-UK",
  },
  {
    id: "veh-02",
    plateNo: "DHL-T-404",
    model: "Scania P280 ColdChain Rigid",
    type: "Refrigerated Cargo Truck",
    status: "En Route",
    driverId: "drv-102",
    driverName: "Aisha Bello",
    fuelLevelPct: 65,
    mileageKm: 112450,
    nextServiceDate: "2026-08-28",
    maxPayloadKg: 7500,
    lastInspectionPassed: true,
    gpsDeviceId: "GPS-TRK-404-NG",
  },
  {
    id: "veh-03",
    plateNo: "DHL-V-210",
    model: "Ford Transit Custom EcoBlue",
    type: "Express Courier Van",
    status: "Available",
    driverId: "drv-103",
    driverName: "David Chen",
    fuelLevelPct: 94,
    mileageKm: 24180,
    nextServiceDate: "2026-10-02",
    maxPayloadKg: 1200,
    lastInspectionPassed: true,
    gpsDeviceId: "GPS-TRK-210-US",
  },
  {
    id: "veh-04",
    plateNo: "DHL-EV-05",
    model: "Renault Master E-Tech Electric",
    type: "Electric Cargo Van",
    status: "En Route",
    driverId: "drv-104",
    driverName: "Sophie Martin",
    fuelLevelPct: 48,
    mileageKm: 18200,
    nextServiceDate: "2026-11-10",
    maxPayloadKg: 1100,
    lastInspectionPassed: true,
    gpsDeviceId: "GPS-TRK-005-FR",
  },
  {
    id: "veh-05",
    plateNo: "DHL-F-882",
    model: "MAN TGX 18.510 Euro 6d",
    type: "Articulated Freighter",
    status: "In-Maintenance",
    driverId: "drv-105",
    driverName: "Klaus Schmidt",
    fuelLevelPct: 15,
    mileageKm: 340900,
    nextServiceDate: "2026-08-09",
    maxPayloadKg: 24000,
    lastInspectionPassed: false,
    gpsDeviceId: "GPS-TRK-882-DE",
  },
  {
    id: "veh-06",
    plateNo: "DHL-V-118",
    model: "Toyota HiAce High-Roof",
    type: "Compact Delivery Sprinter",
    status: "Available",
    driverId: "drv-106",
    driverName: "Taro Tanaka",
    fuelLevelPct: 100,
    mileageKm: 56300,
    nextServiceDate: "2026-09-30",
    maxPayloadKg: 1400,
    lastInspectionPassed: true,
    gpsDeviceId: "GPS-TRK-118-JP",
  },
];

export const INITIAL_ROUTES: RoutePlan[] = [
  {
    id: "rt-101",
    name: "London West Corridor Rapid Express",
    zone: "Zone 1 (Greater London)",
    totalStops: 18,
    completedStops: 14,
    distanceKm: 92.4,
    estDurationHours: 6.5,
    assignedDriverName: "Marcus Vance",
    status: "In Progress",
    originHub: "Slough Distribution Center",
    destinationHub: "Central London Hub",
    efficiencyScorePct: 94.2,
  },
  {
    id: "rt-102",
    name: "Lagos Island & Port Commercial Express",
    zone: "Zone 4 (Lagos Metro)",
    totalStops: 12,
    completedStops: 9,
    distanceKm: 48.0,
    estDurationHours: 5.0,
    assignedDriverName: "Aisha Bello",
    status: "In Progress",
    originHub: "Ikeja Mega Hub",
    destinationHub: "Victoria Island Station",
    efficiencyScorePct: 88.5,
  },
  {
    id: "rt-103",
    name: "Manhattan Midtown & Financial District",
    zone: "Zone 2 (NYC Metro)",
    totalStops: 24,
    completedStops: 24,
    distanceKm: 34.2,
    estDurationHours: 7.0,
    assignedDriverName: "David Chen",
    status: "Completed",
    originHub: "JFK Airport Gateway",
    destinationHub: "Midtown Manhattan Center",
    efficiencyScorePct: 98.1,
  },
  {
    id: "rt-104",
    name: "Paris Intra-muros Zero-Emission Zone",
    zone: "Zone 3 (Paris Center)",
    totalStops: 16,
    completedStops: 11,
    distanceKm: 28.5,
    estDurationHours: 4.8,
    assignedDriverName: "Sophie Martin",
    status: "In Progress",
    originHub: "Orly Cargo Hub",
    destinationHub: "Paris 8e Arrondissement",
    efficiencyScorePct: 92.0,
  },
  {
    id: "rt-105",
    name: "Frankfurt-Nuremberg Heavy Industrial Line",
    zone: "Zone 5 (Bavaria Interstate)",
    totalStops: 6,
    completedStops: 0,
    distanceKm: 228.0,
    estDurationHours: 3.5,
    assignedDriverName: "Pending Dispatch",
    status: "Scheduled",
    originHub: "Frankfurt CargoCity Süd",
    destinationHub: "Nuremberg Plant Center",
    efficiencyScorePct: 96.0,
  },
];

export const INITIAL_INVENTORY: InventoryItem[] = [
  {
    id: "inv-01",
    sku: "PKG-BX-M40",
    name: "DHL Express Box 4 (Medium Rigid)",
    category: "Packaging",
    warehouseHub: "Slough Distribution Center",
    quantity: 1420,
    minThreshold: 300,
    unit: "Units",
    unitCostUsd: 1.85,
    status: "In Stock",
    lastRestocked: "2026-08-01",
  },
  {
    id: "inv-02",
    sku: "CC-ICE-02",
    name: "Cold-Chain Dry Ice Gel Pack (-20°C)",
    category: "Cold-Chain",
    warehouseHub: "Oxford Biocentres Hub",
    quantity: 85,
    minThreshold: 150,
    unit: "Packs",
    unitCostUsd: 6.4,
    status: "Low Stock",
    lastRestocked: "2026-07-20",
  },
  {
    id: "inv-03",
    sku: "SEC-SEAL-89",
    name: "Tamper-Evident High-Security Barcode Seals",
    category: "Security & Seals",
    warehouseHub: "Frankfurt CargoCity Süd",
    quantity: 4800,
    minThreshold: 1000,
    unit: "Seals",
    unitCostUsd: 0.45,
    status: "In Stock",
    lastRestocked: "2026-08-05",
  },
  {
    id: "inv-04",
    sku: "LBL-TH-100",
    name: "Direct Thermal Waybill Rolls (4x6 in)",
    category: "Labels & Hardware",
    warehouseHub: "JFK Airport Gateway",
    quantity: 42,
    minThreshold: 100,
    unit: "Rolls",
    unitCostUsd: 14.2,
    status: "Low Stock",
    lastRestocked: "2026-07-15",
  },
  {
    id: "inv-05",
    sku: "PKG-ENV-S1",
    name: "DHL Flyer Waterproof Padded Envelopes",
    category: "Packaging",
    warehouseHub: "Ikeja Mega Hub",
    quantity: 3200,
    minThreshold: 500,
    unit: "Envelopes",
    unitCostUsd: 0.72,
    status: "In Stock",
    lastRestocked: "2026-08-04",
  },
  {
    id: "inv-06",
    sku: "CC-LOG-01",
    name: "NFC Temperature Logger USB Trackers",
    category: "Cold-Chain",
    warehouseHub: "Oxford Biocentres Hub",
    quantity: 0,
    minThreshold: 50,
    unit: "Devices",
    unitCostUsd: 22.0,
    status: "Out of Stock",
    lastRestocked: "2026-06-30",
  },
];

export const INITIAL_WAREHOUSES: WarehouseHub[] = [
  {
    id: "wh-01",
    name: "DHL Slough European Mega Gateway",
    code: "LHR-GATE-01",
    city: "Slough / London",
    country: "United Kingdom",
    address: "12 Logistics Way, Slough SL1 4XD",
    totalCapacityTons: 450,
    currentUsageTons: 362,
    managerName: "Sarah Jenkins",
    contactPhone: "+44 20 8899 4400",
    activeDocks: 18,
    totalDocks: 24,
    inboundToday: 142,
    outboundToday: 188,
    status: "Normal Operations",
  },
  {
    id: "wh-02",
    name: "Ikeja Airfreight & Regional Hub",
    code: "LOS-AIR-02",
    city: "Lagos",
    country: "Nigeria",
    address: "Plot 4 Murtala Muhammed Int Airport Rd, Ikeja",
    totalCapacityTons: 280,
    currentUsageTons: 245,
    managerName: "Daniel Kayode",
    contactPhone: "+234 1 270 4400",
    activeDocks: 10,
    totalDocks: 12,
    inboundToday: 89,
    outboundToday: 95,
    status: "High Congestion",
  },
  {
    id: "wh-03",
    name: "Frankfurt CargoCity Süd Transshipment Center",
    code: "FRA-CARGO-03",
    city: "Frankfurt",
    country: "Germany",
    address: "Gebäude 537, CargoCity Süd, 60549 Frankfurt am Main",
    totalCapacityTons: 950,
    currentUsageTons: 710,
    managerName: "Klaus Braun",
    contactPhone: "+49 69 690 7000",
    activeDocks: 36,
    totalDocks: 42,
    inboundToday: 310,
    outboundToday: 290,
    status: "Normal Operations",
  },
  {
    id: "wh-04",
    name: "JFK International Gateway Facility",
    code: "JFK-GATE-04",
    city: "New York",
    country: "United States",
    address: "Building 77, North Boundary Rd, JFK Airport, NY 11430",
    totalCapacityTons: 600,
    currentUsageTons: 490,
    managerName: "Elena Rostova",
    contactPhone: "+1 718 553 8800",
    activeDocks: 22,
    totalDocks: 26,
    inboundToday: 215,
    outboundToday: 230,
    status: "Normal Operations",
  },
  {
    id: "wh-05",
    name: "Paris Orly E-Commerce Sortation Depot",
    code: "ORY-SORT-05",
    city: "Paris / Orly",
    country: "France",
    address: "Zone de Fret 4, 94390 Orly Aérogare",
    totalCapacityTons: 320,
    currentUsageTons: 195,
    managerName: "Luc Moreau",
    contactPhone: "+33 1 49 75 22 00",
    activeDocks: 14,
    totalDocks: 16,
    inboundToday: 110,
    outboundToday: 125,
    status: "Normal Operations",
  },
];

export const INITIAL_INVOICES: InvoiceRecord[] = [
  {
    id: "inv-rec-01",
    invoiceNo: "INV-2026-8801",
    orderId: "ORD-2026-901",
    customerName: "AeroTech Systems Ltd",
    customerEmail: "billing@aerotech-sys.com",
    amountUsd: 135.0,
    paymentType: "Credit Card",
    status: "Paid",
    issueDate: "2026-08-08",
    dueDate: "2026-08-22",
    paidAt: "2026-08-08 08:20",
    itemsSummary: "Overnight Priority Express (14.5 kg Slough -> London)",
  },
  {
    id: "inv-rec-02",
    invoiceNo: "INV-2026-8802",
    orderId: "ORD-2026-884",
    customerName: "BioHealth Pharma",
    customerEmail: "accounts@biohealthpharma.org",
    amountUsd: 190.0,
    paymentType: "Contract 30D",
    status: "Pending",
    issueDate: "2026-08-08",
    dueDate: "2026-09-07",
    itemsSummary: "Temperature Sensitive Medical Cold-Chain Transit",
  },
  {
    id: "inv-rec-03",
    invoiceNo: "INV-2026-8803",
    orderId: "ORD-2026-441",
    customerName: "Jumia Express Retail",
    customerEmail: "settlements@jumia.com",
    amountUsd: 85.0,
    paymentType: "COD",
    status: "COD Collected",
    issueDate: "2026-08-08",
    dueDate: "2026-08-08",
    paidAt: "2026-08-08 14:10",
    itemsSummary: "Electronics Courier (Lagos Ikeja -> Yaba Commercial)",
  },
  {
    id: "inv-rec-04",
    invoiceNo: "INV-2026-8790",
    orderId: "ORD-2026-112",
    customerName: "Manhattan Boutique Imports",
    customerEmail: "finance@manhattanluxury.com",
    amountUsd: 110.0,
    paymentType: "Prepaid",
    status: "Paid",
    issueDate: "2026-08-07",
    dueDate: "2026-08-21",
    paidAt: "2026-08-07 19:00",
    itemsSummary: "Customs Airfreight Express (JFK -> Fifth Ave)",
  },
  {
    id: "inv-rec-05",
    invoiceNo: "INV-2026-8742",
    orderId: "ORD-2026-558",
    customerName: "Siemens Energy AG",
    customerEmail: "ap-logistics@siemens.de",
    amountUsd: 520.0,
    paymentType: "Contract 30D",
    status: "Pending",
    issueDate: "2026-08-08",
    dueDate: "2026-09-08",
    itemsSummary: "Heavy Industrial Freight 140kg (Frankfurt -> Nuremberg)",
  },
  {
    id: "inv-rec-06",
    invoiceNo: "INV-2026-8610",
    orderId: "ORD-2026-089",
    customerName: "Nordic Clean Power",
    customerEmail: "invoices@nordicpower.se",
    amountUsd: 340.0,
    paymentType: "Contract 30D",
    status: "Overdue",
    issueDate: "2026-07-05",
    dueDate: "2026-08-05",
    itemsSummary: "Wind Turbine Sensor Kits Express Delivery",
  },
];

export const INITIAL_TARIFFS: RateTariff[] = [
  {
    id: "trf-01",
    name: "Intra-City Metro Standard",
    zoneFrom: "Zone 1 (Metro Core)",
    zoneTo: "Zone 1 (Metro Core)",
    basePriceUsd: 12.0,
    pricePerKgUsd: 1.5,
    expressMultiplier: 1.4,
    overnightMultiplier: 2.0,
    fuelSurchargePct: 4.5,
    handlingFeeUsd: 3.0,
  },
  {
    id: "trf-02",
    name: "Regional Air Corridor",
    zoneFrom: "Zone 1 (London / UK)",
    zoneTo: "Zone 3 (Paris / EU)",
    basePriceUsd: 45.0,
    pricePerKgUsd: 4.8,
    expressMultiplier: 1.5,
    overnightMultiplier: 2.2,
    fuelSurchargePct: 7.2,
    handlingFeeUsd: 8.5,
  },
  {
    id: "trf-03",
    name: "Transatlantic Air Cargo Express",
    zoneFrom: "Zone 1 (UK / EU Hub)",
    zoneTo: "Zone 2 (US / JFK Gateway)",
    basePriceUsd: 95.0,
    pricePerKgUsd: 8.5,
    expressMultiplier: 1.6,
    overnightMultiplier: 2.5,
    fuelSurchargePct: 9.8,
    handlingFeeUsd: 15.0,
  },
  {
    id: "trf-04",
    name: "Heavy Industrial Ground Freight",
    zoneFrom: "Zone 5 (Interstate Industrial)",
    zoneTo: "Zone 5 (Interstate Industrial)",
    basePriceUsd: 150.0,
    pricePerKgUsd: 1.2,
    expressMultiplier: 1.3,
    overnightMultiplier: 1.8,
    fuelSurchargePct: 8.0,
    handlingFeeUsd: 25.0,
  },
];

export const INITIAL_PERMISSIONS: SystemPermission[] = [
  {
    id: "perm-01",
    name: "Full System Control & Root Configs",
    description:
      "Manage API keys, environment parameters, and master database resets",
    superadmin: true,
    admin: false,
    driver: false,
    customer: false,
  },
  {
    id: "perm-02",
    name: "User Roles & RBAC Matrix Editor",
    description:
      "Grant or revoke permissions across admins, dispatchers, drivers, and users",
    superadmin: true,
    admin: false,
    driver: false,
    customer: false,
  },
  {
    id: "perm-03",
    name: "Dispatch & Order Assignment",
    description:
      "Create waybills, assign drivers, schedule route stops, and reroute deliveries",
    superadmin: true,
    admin: true,
    driver: false,
    customer: false,
  },
  {
    id: "perm-04",
    name: "Fleet & Telematics Management",
    description:
      "Edit vehicle records, fuel calibration, maintenance tickets, and route zones",
    superadmin: true,
    admin: true,
    driver: false,
    customer: false,
  },
  {
    id: "perm-05",
    name: "Invoices, Billing & Tariff Pricing",
    description:
      "Generate client invoices, adjust base tariffs, and reconcile COD cash",
    superadmin: true,
    admin: true,
    driver: false,
    customer: false,
  },
  {
    id: "perm-06",
    name: "Field Delivery & Proof of Delivery (PoD)",
    description:
      "Update shipment milestone status, collect customer e-signatures and OTPs",
    superadmin: true,
    admin: true,
    driver: true,
    customer: false,
  },
  {
    id: "perm-07",
    name: "Public Waybill Tracking & Rate Calculator",
    description:
      "Look up parcel journey, download proof of delivery, contact support",
    superadmin: true,
    admin: true,
    driver: true,
    customer: true,
  },
];

export const INITIAL_AI_GOVERNANCE: AIGovernanceConfig = {
  aiEnabled: true,
  lastModifiedBy: "Alex Rodriguez (Superadmin)",
  lastModifiedAt: "2026-08-14 09:30",
  dataAccessMode: "human_in_the_loop",
  readPermissions: {
    shipments: true,
    fleetAndDrivers: true,
    telemetryAndGPS: true,
    financialsAndTariffs: true,
    alertsAndExceptions: true,
  },
  writePermissions: {
    updateShipmentStatus: true,
    assignDrivers: true,
    createAlerts: true,
    modifyTariffs: false,
  },
  pendingActions: [
    {
      id: "act-001",
      actionType: "update_shipment_status",
      title: 'Advance Shipment DHL-8942-02 to "In Transit"',
      description:
        "AI detected driver David Chen completed pickup at Frankfurt Air Cargo (FRA-02). Proposing milestone transition to In Transit.",
      payload: {
        shipmentId: "ship-002",
        trackingId: "DHL-8942-02",
        newStatus: "In Transit",
        location: "Frankfurt Air Cargo Terminal",
        note: "AI Dispatch: Staging completed, carrier en route to Munich",
      },
      status: "pending",
      timestamp: "2026-08-14 09:15",
      proposerPrompt: "Check status of DHL-8942-02 and expedite if ready",
    },
    {
      id: "act-002",
      actionType: "create_route_alert",
      title: "Dispatch High-Priority Weather Advisory for Route A-8",
      description:
        "Severe weather advisory for Alpine Pass (MUC-01 corridor). Proposing system-wide alert dispatch to all on-duty drivers.",
      payload: {
        alertType: "weather",
        alertSeverity: "high",
        alertMessage:
          "Alpine storm warning: Route A-8 visibility under 50m. Drivers advised to activate hazard protocols.",
        shipmentId: "ship-001",
        trackingId: "DHL-8942-01",
      },
      status: "pending",
      timestamp: "2026-08-14 09:22",
      proposerPrompt: "Alert drivers about the heavy snowfall on Route A-8",
    },
  ],
  auditLogs: [
    {
      id: "log-101",
      timestamp: "2026-08-14 09:05",
      actor: "AI Dispatch Copilot",
      action: "Read: Active Telematics & Waybill Database",
      details:
        "Retrieved real-time GPS locations of 4 drivers and 6 priority consignments",
      status: "Executed",
    },
    {
      id: "log-102",
      timestamp: "2026-08-14 09:15",
      actor: "AI Dispatch Copilot",
      action: "Draft: Status Update for DHL-8942-02",
      details:
        'Queued pending status change to "In Transit" awaiting SuperAdmin human approval',
      status: "Approved",
    },
    {
      id: "log-103",
      timestamp: "2026-08-14 09:22",
      actor: "AI Dispatch Copilot",
      action: "Draft: Weather Alert for Route A-8",
      details: "Queued weather exception advisory awaiting SuperAdmin sign-off",
      status: "Approved",
    },
  ],
};
